config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "pages#home"

  get "/home", to: "pages#home", as: "home"
  get "/insumos", to: "pages#insumos", as: "insumos"
  get "/colaboradores", to: "pages#colaboradores", as: "colaboradores"
  get "/produtos", to: "pages#produtos", as: "produtos"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def insumos
  end
  
  def colaboradores
  end

  def produtos
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnacoApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%# Colocar footer só na homepage %>
    <%# <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/colaboradores.html.erb
<div class="main-container">

    <%# sidebar %>
    <div class='sidebar'>

        <%= image_tag 'logo_rest.png', class: "d-grid gap-2 col-10 mx-auto mb-3" %>

        <div class="d-grid gap-2 col-10 mx-auto">
            <%= link_to 'Dashboard', '#', class: 'btn btn-primary' %>

            <button class="btn btn-primary border border-white border-3" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFornecedores" aria-expanded="false" aria-controls="collapseFornecedores">Fornecedores</button>
            <div class="collapse" id="collapseFornecedores">
                <div class="card align-items-end p-0 border-0 card-bg" style="background-color: rgba(255, 0, 0, 0)";>
                    <%= link_to 'Insumos', insumos_path, class: 'btn btn-primary col-10 mb-2' %>
                    <%= link_to 'Colaboradores', colaboradores_path, class: 'btn btn-primary col-10 mb-2 border border-white border-3' %>
                </div>
            </div>

            <%= link_to 'Produtos', produtos_path, class: 'btn btn-primary' %>
            <%= link_to 'Tabela de Preços', '#', class: 'btn btn-primary' %>
        </div>
    </div>

    <%# Main %>
    <div class='container py-3'>
        <div class='container bg-white shadow p-2 mb-3 bg-body-tertiary rounded'>
            <div class='d-grid gap-2 d-md-flex justify-content-md-center'>
                <h1 class='mb-2'>Colaboradores</h1>
            </div>
            <div class='d-grid gap-2 d-md-flex justify-content-md-right'>
                <button type="button" class="btn btn-success my-2">NOVO COLABORADOR</button>
                <button type="button" class="btn btn-dark my-2">HISTÓRICO DE COLABORADORES</button>
            </div>
            <%# Search bar %>
            <%= render "shared/searchbar" %>
        </div>

        <%# Cards %>
        <div class="row row-cols-1 row-cols-md-5 g-4">
            <div class="col">
                <div class="card h-100">
                    <img src="https://media.istockphoto.com/id/1281232665/pt/foto/young-caucasian-male-courier-wearing-protective-face-mask.jpg?s=612x612&w=0&k=20&c=H9aRko6H8kWXGLYD287Q0_iwD1o_3xwEmnTsOwXYS_A=" class="object-fit-scale" alt="...">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-auto">
                            <div class='row'>
                                <div class='col-12'>10/08/2023</div>
                                <div class='col-12 card-title'><h5><u>Ruan</u></h5></div>
                            </div>
                            <div class='row'>
                                <p>
                                    <b>Função:</b> Motoboy<br>
                                    <b>Contratação:</b> Freelancer<br>
                                    <b>Valor:</b> R$ 95,00 /dia<br>
                                    <b>Custo Esp.:</b> 11,87 R$/h<br>
                                </p>
                            </div>
                        </div>
                        <div class="w-100 d-grid gap-2 d-md-flex justify-content-center">
                            <button type="button" class="btn btn-outline-info">Editar</button>
                            <button type="button" class="btn btn-outline-danger">Deletar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="https://media.istockphoto.com/id/1268305464/pt/foto/portrait-of-a-confident-senior-baker-standing-in-a-commercial-kitchen-with-arms-crossed.webp?b=1&s=170667a&w=0&k=20&c=pv6gaCaxA6U3Ia1AAsOf9Ky4dSRbA1iRjkm3kRPOlB4=" class="object-fit-scale" alt="...">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-auto">
                            <div class='row'>
                                <div class='col-12'>10/08/2023</div>
                                <div class='col-12 card-title'><h5><u>Thaís</u></h5></div>
                            </div>
                            <div class='row'>
                                <p>
                                    <b>Função:</b> Cozinheira<br>
                                    <b>Contratação:</b> Freelancer<br>
                                    <b>Valor:</b> R$ 150,00 /dia<br>
                                    <b>Custo Esp.:</b> 18,75 R$/h<br>
                                </p>
                            </div>
                        </div>
                        <div class="w-100 d-grid gap-2 d-md-flex justify-content-center">
                            <button type="button" class="btn btn-outline-info">Editar</button>
                            <button type="button" class="btn btn-outline-danger">Deletar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="https://media.istockphoto.com/id/468874388/pt/foto/homem-motociclista.jpg?s=612x612&w=0&k=20&c=WeXte08sSI1DzKpXN2jg0tg33e7aImFwR7VFSQc2JQY=" class="object-fit-scale" alt="...">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-auto">
                            <div class='row'>
                                <div class='col-12'>10/08/2023</div>
                                <div class='col-12 card-title'><h5><u>Caio</u></h5></div>
                            </div>
                            <div class='row'>
                                <p>
                                    <b>Função:</b> Motoboy<br>
                                    <b>Contratação:</b> Freelancer<br>
                                    <b>Valor:</b> R$ 105,00 /dia<br>
                                    <b>Custo Esp.:</b> 13,12 R$/h<br>
                                </p>
                            </div>
                        </div>
                        <div class="w-100 d-grid gap-2 d-md-flex justify-content-center">
                            <button type="button" class="btn btn-outline-info">Editar</button>
                            <button type="button" class="btn btn-outline-danger">Deletar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="https://media.istockphoto.com/id/1259095163/pt/foto/happy-businesswoman-using-mobile-and-laptop-while-working-at-home.webp?b=1&s=170667a&w=0&k=20&c=y4d2gchgJLVcG1av3lK4e-7v4CX4K9ubmkMFMVglhl4=" class="object-fit-scale" alt="...">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-auto">
                            <div class='row'>
                                <div class='col-12'>10/08/2023</div>
                                <div class='col-12 card-title'><h5><u>Carolina</u></h5></div>
                            </div>
                            <div class='row'>
                                <p>
                                    <b>Função:</b> Atendente<br>
                                    <b>Contratação:</b> CLT<br>
                                    <b>Valor:</b> R$ 1.500,00 /mês<br>
                                    <b>Custo Esp.:</b> 8,52 R$/h<br>
                                </p>
                            </div>
                        </div>
                        <div class="w-100 d-grid gap-2 d-md-flex justify-content-center">
                            <button type="button" class="btn btn-outline-info">Editar</button>
                            <button type="button" class="btn btn-outline-danger">Deletar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/home.html.erb
<h1>HOME</h1>

app/views/pages/insumos.html.erb
<div class="main-container">

    <%# sidebar %>
    <div class='sidebar'>

        <%= image_tag 'logo_rest.png', class: "d-grid gap-2 col-10 mx-auto mb-3" %>

        <div class="d-grid gap-2 col-10 mx-auto">
            <%= link_to 'Dashboard', '#', class: 'btn btn-primary' %>

            <button class="btn btn-primary border border-white border-3" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFornecedores" aria-expanded="false" aria-controls="collapseFornecedores">Fornecedores</button>
            <div class="collapse" id="collapseFornecedores">
                <div class="card align-items-end p-0 border-0 card-bg" style="background-color: rgba(255, 0, 0, 0)";>
                    <%= link_to 'Insumos', insumos_path, class: 'btn btn-primary col-10 mb-2 border border-white border-3' %>
                    <%= link_to 'Colaboradores', colaboradores_path, class: 'btn btn-primary col-10 mb-2' %>
                </div>
            </div>

            <%= link_to 'Produtos', produtos_path, class: 'btn btn-primary' %>
            <%= link_to 'Tabela de Preços', '#', class: 'btn btn-primary' %>
        </div>
    </div>

    <%# Main %>
    <div class='container py-3'>
        <div class='container bg-white shadow p-2 mb-3 bg-body-tertiary rounded'>
            <div class='d-grid gap-2 d-md-flex justify-content-md-center'>
                <h1 class='mb-2'>Insumos</h1>
            </div>
            <div class='d-grid gap-2 d-md-flex justify-content-md-right'>
                <button type="button" class="btn btn-success my-2">NOVO INSUMO</button>
                <button type="button" class="btn btn-dark my-2">HISTÓRICO DE COMPRAS</button>
            </div>
            <%# Search bar %>
            <%= render "shared/searchbar" %>
        </div>

        <%# Cards %>
        <div class="row row-cols-1 row-cols-md-5 g-4">
            <div class="col">
                <div class="card h-100">
                    <img src="https://media.istockphoto.com/id/621712648/pt/foto/green-lectuce-produce-green-vegetable.jpg?s=2048x2048&w=is&k=20&c=JVntYJp6FfVvrPZhJwQphNTftWTedLGSl48iiV1X4OU=" class="object-fit-scale" alt="...">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-auto">
                            <div class='row'>
                                <div class='col-12'>10/08/2023</div>
                                <div class='col-12 card-title'><h5><u>Alface</u></h5></div>
                            </div>
                            <div class='row'>
                                <p>
                                    <b>Valor:</b> R$ 5,18<br>
                                    <b>Quantidade:</b> 1,00 kg<br>
                                    <b>Custo Esp.:</b> 5,18 R$/kg<br>
                                    <b>Fornecedor:</b><br>Supermercado Carrossel
                                </p>
                            </div>
                        </div>
                        <div class="w-100 d-grid gap-2 d-md-flex justify-content-center">
                            <button type="button" class="btn btn-outline-info">Editar</button>
                            <button type="button" class="btn btn-outline-danger">Deletar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Y2hlZXNlJTIwbXVzc2FyZWxhfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60" class="object-fit-scale" alt="...">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-auto">
                            <div class='row'>
                                <div class='col-12'>10/08/2023</div>
                                <div class='col-12 card-title'><h5><u>Mussarela</u></h5></div>
                            </div>
                            <div class='row'>
                                <p>
                                    <b>Valor:</b> R$ 80,00<br>
                                    <b>Quantidade:</b> 2,00 kg<br>
                                    <b>Custo Esp.:</b> 40,00 R$/kg<br>
                                    <b>Fornecedor:</b><br>Fazenda Registro
                                </p>
                            </div>
                        </div>
                        <div class="w-100 d-grid gap-2 d-md-flex justify-content-center">
                            <button type="button" class="btn btn-outline-info">Editar</button>
                            <button type="button" class="btn btn-outline-danger">Deletar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="https://media.istockphoto.com/id/836486634/pt/foto/little-red-cherry-tomatoes-nature-background.jpg?s=1024x1024&w=is&k=20&c=p-O_IE23ZRc02O2qIuQwLs-StCEIG63m3z1_gWb3qsk=" class="object-fit-scale" alt="...">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-auto">
                            <div class='row'>
                                <div class='col-12'>10/08/2023</div>
                                <div class='col-12 card-title'><h5><u>Tomate</u></h5></div>
                            </div>
                            <div class='row'>
                                <p>
                                    <b>Valor:</b> R$ 4,74<br>
                                    <b>Quantidade:</b> 1,20 kg<br>
                                    <b>Custo Esp.:</b> 3,95 R$/kg<br>
                                    <b>Fornecedor:</b><br>Supermercado Carrossel
                                </p>
                            </div>
                        </div>
                        <div class="w-100 d-grid gap-2 d-md-flex justify-content-center">
                            <button type="button" class="btn btn-outline-info">Editar</button>
                            <button type="button" class="btn btn-outline-danger">Deletar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="https://media.istockphoto.com/id/148229297/pt/foto/grilling-hamb%C3%BArgueres.webp?b=1&s=170667a&w=0&k=20&c=3RLAB456NpIPwJXeOwFAgjRTZJmIbN1hCCdC_ZNGXFM=" class="object-fit-scale" alt="...">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-auto">
                            <div class='row'>
                                <div class='col-12'>10/08/2023</div>
                                <div class='col-12 card-title'><h5><u>Carne</u></h5></div>
                            </div>
                            <div class='row'>
                                <p>
                                    <b>Valor:</b> R$ 260,00<br>
                                    <b>Quantidade:</b> 10,00 kg<br>
                                    <b>Custo Esp.:</b> 26,00 R$/kg<br>
                                    <b>Fornecedor:</b><br>Açougue Tigrinho
                                </p>
                            </div>
                        </div>
                        <div class="w-100 d-grid gap-2 d-md-flex justify-content-center">
                            <button type="button" class="btn btn-outline-info">Editar</button>
                            <button type="button" class="btn btn-outline-danger">Deletar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="https://media.istockphoto.com/id/472093755/pt/foto/escaldantes-bacon-em-uma-panela-de-fritura.webp?b=1&s=170667a&w=0&k=20&c=ZERDV171lsimCy2rZJIUz5Gn5YhFtfAkWWKrCtb8P54=" class="object-fit-scale" alt="...">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-auto">
                            <div class='row'>
                                <div class='col-12'>10/08/2023</div>
                                <div class='col-12 card-title'><h5><u>Bacon</u></h5></div>
                            </div>
                            <div class='row'>
                                <p>
                                    <b>Valor:</b> R$ 77,91<br>
                                    <b>Quantidade:</b> 2,00 kg<br>
                                    <b>Custo Esp.:</b> 38,96 R$/kg<br>
                                    <b>Fornecedor:</b><br>Mercado do Léo
                                </p>
                            </div>
                        </div>
                        <div class="w-100 d-grid gap-2 d-md-flex justify-content-center">
                            <button type="button" class="btn btn-outline-info">Editar</button>
                            <button type="button" class="btn btn-outline-danger">Deletar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="https://media.istockphoto.com/id/1173374630/pt/foto/blank-opened-and-closed-craft-burger-box-mockup-side-view.webp?b=1&s=170667a&w=0&k=20&c=jSlRtQGLnn2rym2W-hNj-efbECbRZaUMVQFP5krxXyU=" class="object-fit-scale" alt="...">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-auto">
                            <div class='row'>
                                <div class='col-12'>10/08/2023</div>
                                <div class='col-12 card-title'><h5><u>Embalagem de Hamburguer</u></h5></div>
                            </div>
                            <div class='row'>
                                <p>
                                    <b>Valor:</b> R$ 37,50 <br>
                                    <b>Quantidade:</b> 50 un.<br>
                                    <b>Custo Esp.:</b> 0,75 R$/un.<br>
                                    <b>Fornecedor:</b><br>Bel Embalagens
                                </p>
                            </div>
                        </div>
                        <div class="w-100 d-grid gap-2 d-md-flex justify-content-center">
                            <button type="button" class="btn btn-outline-info">Editar</button>
                            <button type="button" class="btn btn-outline-danger">Deletar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="https://media.istockphoto.com/id/545800796/pt/foto/latas-de-bebidas.webp?b=1&s=170667a&w=0&k=20&c=kQmRvYZ-07rSEIawhneaDfpB4NZCAMM9UmKf0ZQJRvo=" class="object-fit-scale" alt="...">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-auto">
                            <div class='row'>
                                <div class='col-12'>10/08/2023</div>
                                <div class='col-12 card-title'><h5><u>Coca-Cola Lata</u></h5></div>
                            </div>
                            <div class='row'>
                                <p>
                                    <b>Valor:</b> R$ 40,00 <br>
                                    <b>Quantidade:</b> 12,00 un.<br>
                                    <b>Custo Esp.:</b> 3,33 R$/un.<br>
                                    <b>Fornecedor:</b><br>Femsa
                                </p>
                            </div>
                        </div>
                        <div class="w-100 d-grid gap-2 d-md-flex justify-content-center">
                            <button type="button" class="btn btn-outline-info">Editar</button>
                            <button type="button" class="btn btn-outline-danger">Deletar</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <img src="https://media.istockphoto.com/id/155130498/pt/foto/bloco-de-queijo-cheddar.webp?b=1&s=170667a&w=0&k=20&c=Z6jhxbwQ8hOsDE7uojNWzs0X3psRPjYl0uJ1HOmh8XQ=" class="object-fit-scale" alt="...">
                    <div class="card-body d-flex flex-column">
                        <div class="mb-auto">
                            <div class='row'>
                                <div class='col-12'>10/08/2023</div>
                                <div class='col-12 card-title'><h5><u>Cheddar</u></h5></div>
                            </div>
                            <div class='row'>
                                <p>
                                    <b>Valor:</b> R$ 133,50 <br>
                                    <b>Quantidade:</b> 3,00 kg<br>
                                    <b>Custo Esp.:</b> 44,50 R$/kg<br>
                                    <b>Fornecedor:</b><br>Ecila
                                </p>
                            </div>
                        </div>
                        <div class="w-100 d-grid gap-2 d-md-flex justify-content-center">
                            <button type="button" class="btn btn-outline-info">Editar</button>
                            <button type="button" class="btn btn-outline-danger">Deletar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer row">
    <div class="col-12 my-3 p-0 text-center">
        <%= link_to "#", class: "footer-brand" do %>
            <%= image_tag 'logo_laranja.png' %>
        <% end %>
    </div>

    <div class="col-12 p-0 d-flex justify-content-center text-center footer-links">
        <p>
            CNPJ: 13.131.131/0001-13<br>
            Av. Fernando Costa, nº 50, Itanhandu/MG | CEP 37.464-000<br>
            contato@snaco.com.br<br>
            <a href="#" target="_blank"><i class="fa-brands fa-whatsapp"></i></a> (35) 9.9999.9999
        </p>
    </div>    
  
    <div class="footer-links col-12 my-2 p-0 justify-content-center">
        <a href="#" target="_blank"><i class="fab fa-twitter"></i></a>
        <a href="#" target="_blank"><i class="fab fa-facebook"></i></a>
        <a href="#" target="_blank"><i class="fab fa-instagram"></i></a>
        <a href="#" target="_blank"><i class="fab fa-youtube"></i></a>
        <a href="#" target="_blank"><i class="fab fa-linkedin"></i></a>
        <a href="#" target="_blank"><i class="fab fa-github"></i></a>
    </div>

    <div class="text-center pt-0 px-0 pb-3">
        <p class="text-secondary m-0">Copyright © 2023 All Rights Reserved by snaco.</p>
    </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-snaco">
    <div class="container-fluid">

        <%= link_to "#", class: "navbar-brand mx-2 px-3" do %>
            <%= image_tag 'logo.png' %>
        <% end %>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item dropdown">
                    <%= image_tag 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGJ1c3NpbmVzcyUyMHdvbWFufGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <%= link_to "Perfil", "#", class: "dropdown-item" %>
                        <%= link_to "Sair", "#", class: "dropdown-item" %>
                    </div>
                </li>
            </ul>
        </div>
        
    </div>
</div>

app/views/shared/_searchbar.html.erb
<%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form-control form-group mx-0 my-2">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>